[tool.poetry]
name = "lessons-django"
version = "0.1.0"
description = ""
authors = ["timur <timurka.t.r@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
